### ISSUE TITLE
java.io.File.canWrite() is not sufficient to test whether ".cpcache" dir can be created

### ISSUE THREAD

**Issue by jdjohnston** [borkdude/deps.clj#120] opened 2023-12-20 22:43 UTC
This is an issue on Windows 7. Can't say if it's true for newer Windows or other OSes.

I was looking for a test case to try verify that I was actually using `1.11.1.1429` by setting `DEPS_CLJ_TOOLS_VERSION` as you suggested. One new item is the handling of `.cpcache` if the `cwd` isn't writable. `deps.clj` uses `java.io.File.canWrite()`, but that doesn't always work, which is easy to demonstrate in `bb`.

I set `C:\Users\JDJ\tmp\xper` such that I didn't have write or dir creation privileges in `xper`.  I wasn't surprised that `1.11.1.1413` had problems, but `1.11.1.1429` was supposed to handle that case. However, I got the same error. After inspecting the Clojure code, I tried the following in `bb`:

> C:\Users\JDJ\tmp\xper
λ bb
Babashka v1.3.186 REPL.
Use :repl/quit or :repl/exit to quit the REPL.
Clojure rocks, Bash reaches.
>
>user=> (-> (io/file ".") (.canWrite))
true
user=> (fs/create-dir ".cpache")
java.nio.file.AccessDeniedException: .cpache [at <repl>:2:1]
user=>

Please ignore the typo (".cpache").  :)

**Comment by borkdude** [comment] 2023-12-20 22:47
I'm open to a PR which fixes this. Bonus points for a test.

**Comment by jdjohnston** [comment] 2023-12-21 00:22
Not sure when I'd have a chance to write up a PR. Test in Linux is, of course, easy: `mkdir DIR; chmod 0555 DIR`. Windows: *shrug*

As for code, I think you already have it: `babashka.fs/writable?` Without using `babashka.fs` directly here's another `bb` snippet [*]:

> user=> (import 'java.nio.file.Files)
java.nio.file.Files                               
user=> (-> "." io/file (.toPath) Files/isWritable)
false

Not sure if there are any corner cases, but this works for `R/O` dirs in both Windows 7 & Linux, doing some _quick_ tests.

[*] Thanks so much for `bb`. It makes experimenting in the Clojureverse not only easy, but downright fun!

**Comment by borkdude** [comment] 2023-12-21 09:46
So there is a difference between `canWrite` and `isWriteable`, that is the crux?

**Comment by jdjohnston** [comment] 2023-12-21 16:39
Seems to be, based on some _lite_ testing on Windows 7 & Debian Linux. Not
sure they're supposed to be different, but that's a Java issue

**Comment by jlesquembre** [comment] 2023-12-21 18:28
@jdjohnston Can you provide an example where `canWrite` and `isWriteable` return a different value? I can't reproduce it.

**Comment by jdjohnston** [comment] 2023-12-21 18:43
As my original Issue description says, this might be specific to Winsows,
maybe even just older Windows. I used Windows Explorer to remove write &
dir creation privileges from the test dir. In that dir there is
consistently a difference. Sorry I can't provide a command-line sequence,
but I had to use the GUI to remove the privileges

**Comment by jdjohnston** [comment] 2023-12-21 19:33
I think I may have confused things earlier when I mentioned Debian Linux. I
used Linux to verify that isWritable would give the desired result, _not_
that it gave a different result from canWrite. As one would hope, for a
simple test at least, they give the same result on Linux.

So sorry for any confusion! :(

**Comment by borkdude** [comment] 2023-12-21 20:19
Is the summary that we should switch to `java.nio` isWritable and then we can close the issue? Happy to do this.

**Comment by jdjohnston** [comment] 2023-12-21 20:24
Sounds good to me!

**Closed** 2023-12-21 20:27 UTC

**Comment by jdjohnston** [comment] 2023-12-22 05:09
Just tried the build artifact on my R/O Win 7 dir. As hoped for, deps.clj
used the cache_dir since the cwd wasn't writable.

Is there another corner case? Couldn't say, but at least _this_ one is now
accounted for.

Thanks & Merry Christmas!

**Comment by borkdude** [comment] 2024-01-09 14:40
New release is available

**Comment by jdjohnston** [comment] 2024-01-10 20:57
@borkdude The new release recognizes that the test dir is R/O, as desired. No obvious regression :)
